/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

pub enum QTYPE {
    A = 1,
    NS = 2,
    MD = 3,
    MF = 4,
    CNAME = 5,
    SOA = 6,
    MB = 7,
    MG = 8,
    MR = 9,
    NULL = 10,
    WKS = 11,
    PTR = 12,
    HINFO = 13,
    MINFO = 14,
    MX = 15,
    TXT = 16,
    RP = 17,
    AFSDB = 18,
    X25 = 19,
    ISDN = 20,
    RT = 21,
    NSAP = 22,
    NSAP_PTR = 23,
    SIG = 24,
    KEY = 25,
    PX = 26,
    GPOS = 27,
    AAAA = 28,
    LOC = 29,
    NXT = 30,
    EID = 31,
    NIMLOC = 32,
    SRV = 33,
    ATMA = 34,
    NAPTR = 35,
    KX = 36,
    CERT = 37,
    A6 = 38,
    DNAME = 39,
    SINK = 40,
    OPT = 41,
    APL = 42,
    DS = 43,
    SSHFP = 44,
    IPSECKEY = 45,
    RRSIG = 46,
    NSEC = 47,
    DNSKEY = 48,
    DHCID = 49,
    NSEC3 = 50,
    NSEC3PARAM = 51,
    TLSA = 52,
    SMIMEA = 53,
    HIP = 55,
    NINFO = 56,
    RKEY = 57,
    TALINK = 58,
    CDS = 59,
    CDNSKEY = 60,
    OPENPGPKEY = 61,
    CSYNC = 62,
    ZONEMD = 63,
    SVCB = 64,
    HTTPS = 65,
    SPF = 99,
    UINFO = 100,
    UID = 101,
    GID = 102,
    UNSPEC = 103,
    NID = 104,
    L32 = 105,
    L64 = 106,
    LP = 107,
    EUI48 = 108,
    EUI64 = 109,
    TKEY = 249,
    TSIG = 250,
    IXFR = 251,
    AXFR = 252,
    MAILB = 253,
    MAILA = 254,
    ANY = 255,
    URI = 256,
    CAA = 257,
    AVC = 258,
    DOA = 259,
    AMTRELAY = 260,
    TA = 32768,
    DLV = 32769,
}

impl QTYPE {
    pub fn name(&self) -> &'static str {
        return match self {
            QTYPE::A => "A",
            QTYPE::NS => "NS",
            QTYPE::MD => "MD",
            QTYPE::MF => "MF",
            QTYPE::CNAME => "CNAME",
            QTYPE::SOA => "SOA",
            QTYPE::MB => "MB",
            QTYPE::MG => "MG",
            QTYPE::MR => "MR",
            QTYPE::NULL => "NULL",
            QTYPE::WKS => "WKS",
            QTYPE::PTR => "PTR",
            QTYPE::HINFO => "HINFO",
            QTYPE::MINFO => "MINFO",
            QTYPE::MX => "MX",
            QTYPE::TXT => "TXT",
            QTYPE::RP => "RP",
            QTYPE::AFSDB => "AFSDB",
            QTYPE::X25 => "X25",
            QTYPE::ISDN => "ISDN",
            QTYPE::RT => "RT",
            QTYPE::NSAP => "NSAP",
            QTYPE::NSAP_PTR => "NSAP-PTR",
            QTYPE::SIG => "SIG",
            QTYPE::KEY => "KEY",
            QTYPE::PX => "PX",
            QTYPE::GPOS => "GPOS",
            QTYPE::AAAA => "AAAA",
            QTYPE::LOC => "LOC",
            QTYPE::NXT => "NXT",
            QTYPE::EID => "EID",
            QTYPE::NIMLOC => "NIMLOC",
            QTYPE::SRV => "SRV",
            QTYPE::ATMA => "ATMA",
            QTYPE::NAPTR => "NAPTR",
            QTYPE::KX => "KX",
            QTYPE::CERT => "CERT",
            QTYPE::A6 => "A6",
            QTYPE::DNAME => "DNAME",
            QTYPE::SINK => "SINK",
            QTYPE::OPT => "OPT",
            QTYPE::APL => "APL",
            QTYPE::DS => "DS",
            QTYPE::SSHFP => "SSHFP",
            QTYPE::IPSECKEY => "IPSECKEY",
            QTYPE::RRSIG => "RRSIG",
            QTYPE::NSEC => "NSEC",
            QTYPE::DNSKEY => "DNSKEY",
            QTYPE::DHCID => "DHCID",
            QTYPE::NSEC3 => "NSEC3",
            QTYPE::NSEC3PARAM => "NSEC3PARAM",
            QTYPE::TLSA => "TLSA",
            QTYPE::SMIMEA => "SMIMEA",
            QTYPE::HIP => "HIP",
            QTYPE::NINFO => "NINFO",
            QTYPE::RKEY => "RKEY",
            QTYPE::TALINK => "TALINK",
            QTYPE::CDS => "CDS",
            QTYPE::CDNSKEY => "CDNSKEY",
            QTYPE::OPENPGPKEY => "OPENPGPKEY",
            QTYPE::CSYNC => "CSYNC",
            QTYPE::ZONEMD => "ZONEMD",
            QTYPE::SVCB => "SVCB",
            QTYPE::HTTPS => "HTTPS",
            QTYPE::SPF => "SPF",
            QTYPE::UINFO => "UINFO",
            QTYPE::UID => "UID",
            QTYPE::GID => "GID",
            QTYPE::UNSPEC => "UNSPEC",
            QTYPE::NID => "NID",
            QTYPE::L32 => "L32",
            QTYPE::L64 => "L64",
            QTYPE::LP => "LP",
            QTYPE::EUI48 => "EUI48",
            QTYPE::EUI64 => "EUI64",
            QTYPE::TKEY => "TKEY",
            QTYPE::TSIG => "TSIG",
            QTYPE::IXFR => "IXFR",
            QTYPE::AXFR => "AXFR",
            QTYPE::MAILB => "MAILB",
            QTYPE::MAILA => "MAILA",
            QTYPE::ANY => "*",
            QTYPE::URI => "URI",
            QTYPE::CAA => "CAA",
            QTYPE::AVC => "AVC",
            QTYPE::DOA => "DOA",
            QTYPE::AMTRELAY => "AMTRELAY",
            QTYPE::TA => "TA",
            QTYPE::DLV => "DLV"
        }
    }

    pub fn code(&self) -> u16 {
        return match self {
            QTYPE::A => QTYPE::A as u16,
            QTYPE::NS => QTYPE::NS as u16,
            QTYPE::MD => QTYPE::MD as u16,
            QTYPE::MF => QTYPE::MF as u16,
            QTYPE::CNAME => QTYPE::CNAME as u16,
            QTYPE::SOA => QTYPE::SOA as u16,
            QTYPE::MB => QTYPE::MB as u16,
            QTYPE::MG => QTYPE::MG as u16,
            QTYPE::MR => QTYPE::MR as u16,
            QTYPE::NULL => QTYPE::NULL as u16,
            QTYPE::WKS => QTYPE::WKS as u16,
            QTYPE::PTR => QTYPE::PTR as u16,
            QTYPE::HINFO => QTYPE::HINFO as u16,
            QTYPE::MINFO => QTYPE::MINFO as u16,
            QTYPE::MX => QTYPE::MX as u16,
            QTYPE::TXT => QTYPE::TXT as u16,
            QTYPE::RP => QTYPE::RP as u16,
            QTYPE::AFSDB => QTYPE::AFSDB as u16,
            QTYPE::X25 => QTYPE::X25 as u16,
            QTYPE::ISDN => QTYPE::ISDN as u16,
            QTYPE::RT => QTYPE::RT as u16,
            QTYPE::NSAP => QTYPE::NSAP as u16,
            QTYPE::NSAP_PTR => QTYPE::NSAP_PTR as u16,
            QTYPE::SIG => QTYPE::SIG as u16,
            QTYPE::KEY => QTYPE::KEY as u16,
            QTYPE::PX => QTYPE::PX as u16,
            QTYPE::GPOS => QTYPE::GPOS as u16,
            QTYPE::AAAA => QTYPE::AAAA as u16,
            QTYPE::LOC => QTYPE::LOC as u16,
            QTYPE::NXT => QTYPE::NXT as u16,
            QTYPE::EID => QTYPE::EID as u16,
            QTYPE::NIMLOC => QTYPE::NIMLOC as u16,
            QTYPE::SRV => QTYPE::SRV as u16,
            QTYPE::ATMA => QTYPE::ATMA as u16,
            QTYPE::NAPTR => QTYPE::NAPTR as u16,
            QTYPE::KX => QTYPE::KX as u16,
            QTYPE::CERT => QTYPE::CERT as u16,
            QTYPE::A6 => QTYPE::A6 as u16,
            QTYPE::DNAME => QTYPE::DNAME as u16,
            QTYPE::SINK => QTYPE::SINK as u16,
            QTYPE::OPT => QTYPE::OPT as u16,
            QTYPE::APL => QTYPE::APL as u16,
            QTYPE::DS => QTYPE::DS as u16,
            QTYPE::SSHFP => QTYPE::SSHFP as u16,
            QTYPE::IPSECKEY => QTYPE::IPSECKEY as u16,
            QTYPE::RRSIG => QTYPE::RRSIG as u16,
            QTYPE::NSEC => QTYPE::NSEC as u16,
            QTYPE::DNSKEY => QTYPE::DNSKEY as u16,
            QTYPE::DHCID => QTYPE::DHCID as u16,
            QTYPE::NSEC3 => QTYPE::NSEC3 as u16,
            QTYPE::NSEC3PARAM => QTYPE::NSEC3PARAM as u16,
            QTYPE::TLSA => QTYPE::TLSA as u16,
            QTYPE::SMIMEA => QTYPE::SMIMEA as u16,
            QTYPE::HIP => QTYPE::HIP as u16,
            QTYPE::NINFO => QTYPE::NINFO as u16,
            QTYPE::RKEY => QTYPE::RKEY as u16,
            QTYPE::TALINK => QTYPE::TALINK as u16,
            QTYPE::CDS => QTYPE::CDS as u16,
            QTYPE::CDNSKEY => QTYPE::CDNSKEY as u16,
            QTYPE::OPENPGPKEY => QTYPE::OPENPGPKEY as u16,
            QTYPE::CSYNC => QTYPE::CSYNC as u16,
            QTYPE::ZONEMD => QTYPE::ZONEMD as u16,
            QTYPE::SVCB => QTYPE::SVCB as u16,
            QTYPE::HTTPS => QTYPE::HTTPS as u16,
            QTYPE::SPF => QTYPE::SPF as u16,
            QTYPE::UINFO => QTYPE::UINFO as u16,
            QTYPE::UID => QTYPE::UID as u16,
            QTYPE::GID => QTYPE::GID as u16,
            QTYPE::UNSPEC => QTYPE::UNSPEC as u16,
            QTYPE::NID => QTYPE::NID as u16,
            QTYPE::L32 => QTYPE::L32 as u16,
            QTYPE::L64 => QTYPE::L64 as u16,
            QTYPE::LP => QTYPE::LP as u16,
            QTYPE::EUI48 => QTYPE::EUI48 as u16,
            QTYPE::EUI64 => QTYPE::EUI64 as u16,
            QTYPE::TKEY => QTYPE::TKEY as u16,
            QTYPE::TSIG => QTYPE::TSIG as u16,
            QTYPE::IXFR => QTYPE::IXFR as u16,
            QTYPE::AXFR => QTYPE::AXFR as u16,
            QTYPE::MAILB => QTYPE::MAILB as u16,
            QTYPE::MAILA => QTYPE::MAILA as u16,
            QTYPE::ANY => QTYPE::ANY as u16,
            QTYPE::URI => QTYPE::URI as u16,
            QTYPE::CAA => QTYPE::CAA as u16,
            QTYPE::AVC => QTYPE::AVC as u16,
            QTYPE::DOA => QTYPE::DOA as u16,
            QTYPE::AMTRELAY => QTYPE::AMTRELAY as u16,
            QTYPE::TA => QTYPE::TA as u16,
            QTYPE::DLV => QTYPE::DLV as u16,
        }
    }

    pub fn hex(&self) -> String {
        return match self {
            QTYPE::A => format!("{:02x}", QTYPE::A.code()),
            QTYPE::NS => format!("{:02x}", QTYPE::NS.code()),
            QTYPE::MD => format!("{:02x}", QTYPE::MD.code()),
            QTYPE::MF => format!("{:02x}", QTYPE::MF.code()),
            QTYPE::CNAME => format!("{:02x}", QTYPE::CNAME.code()),
            QTYPE::SOA => format!("{:02x}", QTYPE::SOA.code()),
            QTYPE::MB => format!("{:02x}", QTYPE::MB.code()),
            QTYPE::MG => format!("{:02x}", QTYPE::MG.code()),
            QTYPE::MR => format!("{:02x}", QTYPE::MR.code()),
            QTYPE::NULL => format!("{:02x}", QTYPE::NULL.code()),
            QTYPE::WKS => format!("{:02x}", QTYPE::WKS.code()),
            QTYPE::PTR => format!("{:02x}", QTYPE::PTR.code()),
            QTYPE::HINFO => format!("{:02x}", QTYPE::HINFO.code()),
            QTYPE::MINFO => format!("{:02x}", QTYPE::MINFO.code()),
            QTYPE::MX => format!("{:02x}", QTYPE::MX.code()),
            QTYPE::TXT => format!("{:02x}", QTYPE::TXT.code()),
            QTYPE::RP => format!("{:02x}", QTYPE::RP.code()),
            QTYPE::AFSDB => format!("{:02x}", QTYPE::AFSDB.code()),
            QTYPE::X25 => format!("{:02x}", QTYPE::X25.code()),
            QTYPE::ISDN => format!("{:02x}", QTYPE::ISDN.code()),
            QTYPE::RT => format!("{:02x}", QTYPE::RT.code()),
            QTYPE::NSAP => format!("{:02x}", QTYPE::NSAP.code()),
            QTYPE::NSAP_PTR => format!("{:02x}", QTYPE::NSAP_PTR.code()),
            QTYPE::SIG => format!("{:02x}", QTYPE::SIG.code()),
            QTYPE::KEY => format!("{:02x}", QTYPE::KEY.code()),
            QTYPE::PX => format!("{:02x}", QTYPE::PX.code()),
            QTYPE::GPOS => format!("{:02x}", QTYPE::GPOS.code()),
            QTYPE::AAAA => format!("{:02x}", QTYPE::AAAA.code()),
            QTYPE::LOC => format!("{:02x}", QTYPE::LOC.code()),
            QTYPE::NXT => format!("{:02x}", QTYPE::NXT.code()),
            QTYPE::EID => format!("{:02x}", QTYPE::EID.code()),
            QTYPE::NIMLOC => format!("{:02x}", QTYPE::NIMLOC.code()),
            QTYPE::SRV => format!("{:02x}", QTYPE::SRV.code()),
            QTYPE::ATMA => format!("{:02x}", QTYPE::ATMA.code()),
            QTYPE::NAPTR => format!("{:02x}", QTYPE::NAPTR.code()),
            QTYPE::KX => format!("{:02x}", QTYPE::KX.code()),
            QTYPE::CERT => format!("{:02x}", QTYPE::CERT.code()),
            QTYPE::A6 => format!("{:02x}", QTYPE::A6.code()),
            QTYPE::DNAME => format!("{:02x}", QTYPE::DNAME.code()),
            QTYPE::SINK => format!("{:02x}", QTYPE::SINK.code()),
            QTYPE::OPT => format!("{:02x}", QTYPE::OPT.code()),
            QTYPE::APL => format!("{:02x}", QTYPE::APL.code()),
            QTYPE::DS => format!("{:02x}", QTYPE::DS.code()),
            QTYPE::SSHFP => format!("{:02x}", QTYPE::SSHFP.code()),
            QTYPE::IPSECKEY => format!("{:02x}", QTYPE::IPSECKEY.code()),
            QTYPE::RRSIG => format!("{:02x}", QTYPE::RRSIG.code()),
            QTYPE::NSEC => format!("{:02x}", QTYPE::NSEC.code()),
            QTYPE::DNSKEY => format!("{:02x}", QTYPE::DNSKEY.code()),
            QTYPE::DHCID => format!("{:02x}", QTYPE::DHCID.code()),
            QTYPE::NSEC3 => format!("{:02x}", QTYPE::NSEC3.code()),
            QTYPE::NSEC3PARAM => format!("{:02x}", QTYPE::NSEC3PARAM.code()),
            QTYPE::TLSA => format!("{:02x}", QTYPE::TLSA.code()),
            QTYPE::SMIMEA => format!("{:02x}", QTYPE::SMIMEA.code()),
            QTYPE::HIP => format!("{:02x}", QTYPE::HIP.code()),
            QTYPE::NINFO => format!("{:02x}", QTYPE::MINFO.code()),
            QTYPE::RKEY => format!("{:02x}", QTYPE::RKEY.code()),
            QTYPE::TALINK => format!("{:02x}", QTYPE::TALINK.code()),
            QTYPE::CDS => format!("{:02x}", QTYPE::CDS.code()),
            QTYPE::CDNSKEY => format!("{:02x}", QTYPE::CDNSKEY.code()),
            QTYPE::OPENPGPKEY => format!("{:02x}", QTYPE::OPENPGPKEY.code()),
            QTYPE::CSYNC => format!("{:02x}", QTYPE::CSYNC.code()),
            QTYPE::ZONEMD => format!("{:02x}", QTYPE::ZONEMD.code()),
            QTYPE::SVCB => format!("{:02x}", QTYPE::SVCB.code()),
            QTYPE::HTTPS => format!("{:02x}", QTYPE::HTTPS.code()),
            QTYPE::SPF => format!("{:02x}", QTYPE::SPF.code()),
            QTYPE::UINFO => format!("{:02x}", QTYPE::UINFO.code()),
            QTYPE::UID => format!("{:02x}", QTYPE::UID.code()),
            QTYPE::GID => format!("{:02x}", QTYPE::GID.code()),
            QTYPE::UNSPEC => format!("{:02x}", QTYPE::UNSPEC.code()),
            QTYPE::NID => format!("{:02x}", QTYPE::NID.code()),
            QTYPE::L32 => format!("{:02x}", QTYPE::L32.code()),
            QTYPE::L64 => format!("{:02x}", QTYPE::L64.code()),
            QTYPE::LP => format!("{:02x}", QTYPE::LP.code()),
            QTYPE::EUI48 => format!("{:02x}", QTYPE::EUI48.code()),
            QTYPE::EUI64 => format!("{:02x}", QTYPE::EUI64.code()),
            QTYPE::TKEY => format!("{:02x}", QTYPE::TKEY.code()),
            QTYPE::TSIG => format!("{:02x}", QTYPE::TSIG.code()),
            QTYPE::IXFR => format!("{:02x}", QTYPE::IXFR.code()),
            QTYPE::AXFR => format!("{:02x}", QTYPE::AXFR.code()),
            QTYPE::MAILB => format!("{:02x}", QTYPE::MAILB.code()),
            QTYPE::MAILA => format!("{:02x}", QTYPE::MAILA.code()),
            QTYPE::ANY => format!("{:02x}", QTYPE::ANY.code()),
            QTYPE::URI => format!("{:02x}", QTYPE::URI.code()),
            QTYPE::CAA => format!("{:02x}", QTYPE::CAA.code()),
            QTYPE::AVC => format!("{:02x}", QTYPE::AVC.code()),
            QTYPE::DOA => format!("{:02x}", QTYPE::DOA.code()),
            QTYPE::AMTRELAY => format!("{:02x}", QTYPE::AMTRELAY.code()),
            QTYPE::TA => format!("{:02x}", QTYPE::TA.code()),
            QTYPE::DLV => format!("{:02x}", QTYPE::DLV.code()),
        }
    }
}
